# Generated by Django 3.2.9 on 2022-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('carrier', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('amount_of_delays', models.IntegerField()),
                ('amount_of_flights', models.IntegerField()),
                ('mean_of_delay', models.DecimalField(decimal_places=5, max_digits=19)),
                ('number_of_flights', models.IntegerField()),
                ('number_of_accidents', models.IntegerField()),
                ('chance_of_delay', models.DecimalField(decimal_places=8, max_digits=19)),
                ('chance_of_accident', models.DecimalField(decimal_places=8, max_digits=19)),
            ],
            options={
                'db_table': 'widok_lot_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delays',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dfyear', models.IntegerField(blank=True, null=True)),
                ('dfmonth', models.IntegerField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=2, null=True)),
                ('dfop_carrier', models.CharField(blank=True, max_length=300, null=True)),
                ('dfmeantimeofdelay', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dfdelaypercent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dfnumofflights', models.IntegerField(blank=True, null=True)),
                ('dfnumofdelay', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delays',
                'managed': False,
            },
        ),
    ]
