# Generated by Django 3.2.9 on 2022-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
