# Generated by Django 3.2.9 on 2022-05-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20220504_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='number_of_flights_2',
            new_name='number_of_accidents_2',
        ),
    ]
